apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-deploy
  template:
    metadata:
      name: productserviceapp-deploy
      labels:
        env: prod
        app: product-service-deploy
        app.kubernetes.io/name: product-service-deploy
    spec:
      containers:
        - name: product-service-deploy
          image: astmatikerne/ecommerce-product:latest
          ports:
            - containerPort: 8080
              name: http-web-api
              