apiVersion: v1
kind: Service
metadata:
  name: product-lb-service
spec:
  selector:
    app.kubernetes.io/name: product-service-deploy
  ports:
    - name: productservice-ports
      protocol: TCP
      port: 9092
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-deploy
  template:
    metadata:
      name: productserviceapp-deploy
      labels:
        env: prod
        app: product-service-deploy
        app.kubernetes.io/name: product-service-deploy
    spec:
      containers:
        - name: product-service-deploy
          image: astmatikerne/ecommerce-product:latest
          ports:
            - containerPort: 8080
              name: http-web-api
              
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-mongodb
spec:
  serviceName: product-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: product-mongodb
  template:
    metadata:
      labels:
        app: product-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: product-mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: product-mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi