apiVersion: v1
kind: Service
metadata:
  name: product-lb-service
spec:
  selector:
    app.kubernetes.io/name: product-service-deploy
  ports:
    - name: productservice-ports
      protocol: TCP
      port: 9092
      targetPort: 8080
  type: LoadBalancer


