apiVersion: v1
kind: Secret
metadata:
  name: userdb-secret
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
spec:
  serviceName: user-postgres
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: user-postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: user-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi