apiVersion: v1
kind: Service
metadata:
  name: product-lb-service
spec:
  selector:
    app.kubernetes.io/name: product-service-deploy
  ports:
    - name: productservice-ports
      protocol: TCP
      port: 9092
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-deploy
  template:
    metadata:
      name: userserviceapp-deploy
      labels:
        env: prod
        app: user-service-deploy
        app.kubernetes.io/name: user-service-deploy
    spec:
      containers:
        - name: user-service-deploy
          image: astmatikerne/ecommerce-user:latest
          ports:
            - containerPort: 8080
              name: http-web-api


---

apiVersion: v1
kind: Secret
metadata:
  name: userdb-secret
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-postgres
spec:
  serviceName: user-postgres
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5433
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userdb-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: user-postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: user-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi