apiVersion: v1
kind: Service
metadata:
  name: auth-lb-service
spec:
  selector:
    app.kubernetes.io/name: auth-service-deploy
  ports:
    - name: authservice-ports
      protocol: TCP
      port: 9090
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-deploy
  template:
    metadata:
      name: authserviceapp-deploy
      labels:
        env: prod
        app: auth-service-deploy
        app.kubernetes.io/name: auth-service-deploy
    spec:
      containers:
        - name: auth-service-deploy
          image: astmatikerne/ecommerce-authentication:latest
          ports:
            - containerPort: 8080
              name: http-web-api


---

apiVersion: v1
kind: Secret
metadata:
  name: authdb-secret
type: Opaque
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-postgres
spec:
  serviceName: auth-postgres
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authdb-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: auth-postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: auth-postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
