apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: authservice
  ports:
    - port: 8080
      targetPort: 30002
      nodePort: 30002