apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: astmatikerne/ecommerce-authentication:latest
          ports:
            - containerPort: 8080
