global using Xunit;
global using AutoMapper;
global using Cache;
global using Moq;
global using ProductService.Core.Entities;
global using ProductService.Core.Repositories.Interfaces;
global using ProductService.Core.Services.DTOs;
global using MongoDB.Bson;
global using ProductService.Core.Entities.Helper;