apiVersion: v1
kind: Service
metadata:
  name: auth-lb-service
spec:
  selector:
    app.kubernetes.io/name: auth-service-deploy
  ports:
    - name: authservice-ports
      protocol: TCP
      port: 9090
  type: LoadBalancer

