apiVersion: v1
kind: Service
metadata:
  name: cart-lb-service
spec:
  selector:
    app.kubernetes.io/name: cart-service-deploy
  ports:
    - name: cartservice-ports
      protocol: TCP
      port: 9093
      targetPort: 8080
  type: LoadBalancer
