apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: userservice
  ports:
    - port: 8080
      targetPort: 30001
      nodePort: 30001