apiVersion: v1
kind: Service
metadata:
  name: cart-lb-service
spec:
  selector:
    app.kubernetes.io/name: cart-service-deploy
  ports:
    - name: cartservice-ports
      protocol: TCP
      port: 9093
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service-deploy
  template:
    metadata:
      name: cartserviceapp-deploy
      labels:
        env: prod
        app: cart-service-deploy
        app.kubernetes.io/name: cart-service-deploy
    spec:
      containers:
        - name: cart-service-deploy
          image: astmatikerne/ecommerce-cart:latest
          ports:
            - containerPort: 8080
              name: http-web-api

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cart-mongodb
spec:
  serviceName: cart-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: cart-mongodb
  template:
    metadata:
      labels:
        app: cart-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27018
          volumeMounts:
            - name: cart-mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: cart-mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


