#CI Pipeline 
name: eCommerce - Continuous Development

on:
  push:
    branches: [ "development", "main", "pipeline_setup" ]
    
jobs:
  docker_hub_deploy:
    name: Deploy docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push APIGateway image
        uses: docker/build-push-action@v5
        with:
          file: ././eCommerce/Microservices/APIGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eCommerce-api-gateway:latest
        
      - name: Build and push AuthService image
        uses: docker/build-push-action@v5
        with:
          file: ././eCommerce/Microservices/AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eCommerce-authentication:latest
        
      - name: Build and push CartService image
        uses: docker/build-push-action@v5
        with:
          file: ././eCommerce/Microservices/CartService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eCommerce-cart:latest
          
      - name: Build and push ProductService image
        uses: docker/build-push-action@v5
        with:
          file: ././eCommerce/Microservices/ProductService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eCommerce-product:latest
          
      - name: Build and push UserService image
        uses: docker/build-push-action@v5
        with:
          file: ././eCommerce/Microservices/UserService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eCommerce-user:latest