#CI Pipeline 
name: eCommerce - Continuous Deployment

on:
  push:
    branches: [ "main", "kubernetes_cd_pipeline" ]

jobs:
  azure_kubernetes_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml          
          kubectl apply -f Microservices/AuthService/authservice.k8s.yml
          kubectl apply -f Microservices/CartService/cartservice.k8s.yml
          kubectl apply -f Microservices/ProductService/productservice.k8s.yml
          kubectl apply -f Microservices/UserService/userservice.k8s.yml